# pins.tcl - pin locations for THIS board. Merged into WillFA7.qsf by
# scripts\gen_qsf.ps1. This is the truth about the board, not the comments in
# the VHDL port list. Hand maintained.
set_location_assignment PIN_E1 -to clk_50
set_location_assignment PIN_T3 -to CS_EEprom
set_location_assignment PIN_C8 -to CS_SDcard
set_location_assignment PIN_A13 -to disp_bcd[7]
set_location_assignment PIN_B13 -to disp_bcd[6]
set_location_assignment PIN_A12 -to disp_bcd[5]
set_location_assignment PIN_B12 -to disp_bcd[4]
set_location_assignment PIN_A11 -to disp_bcd[3]
set_location_assignment PIN_B11 -to disp_bcd[2]
set_location_assignment PIN_A10 -to disp_bcd[1]
set_location_assignment PIN_B10 -to disp_bcd[0]
set_location_assignment PIN_B8 -to disp_strobe[3]
set_location_assignment PIN_A8 -to disp_strobe[2]
set_location_assignment PIN_B9 -to disp_strobe[1]
set_location_assignment PIN_A9 -to disp_strobe[0]
set_location_assignment PIN_R14 -to lamp_row_sel
set_location_assignment PIN_T13 -to lamp_strobe_sel
set_location_assignment PIN_B7 -to lamps[7]
set_location_assignment PIN_A6 -to lamps[6]
set_location_assignment PIN_A4 -to lamps[5]
set_location_assignment PIN_T14 -to lamps[4]
set_location_assignment PIN_T15 -to lamps[3]
set_location_assignment PIN_B6 -to lamps[2]
set_location_assignment PIN_A5 -to lamps[1]
set_location_assignment PIN_A7 -to lamps[0]
set_location_assignment PIN_D8 -to MISO
set_location_assignment PIN_K1 -to MOSI
set_location_assignment PIN_F16 -to sol_1_8_sel
set_location_assignment PIN_F15 -to sol_9_16_sel
set_location_assignment PIN_G15 -to sol_spec_sel
set_location_assignment PIN_B16 -to solenoids[7]
set_location_assignment PIN_C15 -to solenoids[6]
set_location_assignment PIN_D16 -to solenoids[5]
set_location_assignment PIN_E10 -to solenoids[4]
set_location_assignment PIN_E11 -to solenoids[3]
set_location_assignment PIN_D15 -to solenoids[2]
set_location_assignment PIN_C16 -to solenoids[1]
set_location_assignment PIN_A15 -to solenoids[0]
set_location_assignment PIN_L1 -to SPI_CLK
set_location_assignment PIN_T9 -to sw_return[7]
set_location_assignment PIN_R10 -to sw_return[6]
set_location_assignment PIN_T10 -to sw_return[5]
set_location_assignment PIN_R11 -to sw_return[4]
set_location_assignment PIN_T11 -to sw_return[3]
set_location_assignment PIN_R12 -to sw_return[2]
set_location_assignment PIN_T12 -to sw_return[1]
set_location_assignment PIN_R13 -to sw_return[0]
set_location_assignment PIN_R4 -to sw_strobe[7]
set_location_assignment PIN_R5 -to sw_strobe[6]
set_location_assignment PIN_T4 -to sw_strobe[5]
set_location_assignment PIN_R6 -to sw_strobe[4]
set_location_assignment PIN_T5 -to sw_strobe[3]
set_location_assignment PIN_R7 -to sw_strobe[2]
set_location_assignment PIN_T6 -to sw_strobe[1]
set_location_assignment PIN_T7 -to sw_strobe[0]
set_location_assignment PIN_B1 -to Dip_Ret_3
set_location_assignment PIN_C3 -to Dip_Ret_2
set_location_assignment PIN_D1 -to Dip_Ret_1
set_location_assignment PIN_P2 -to DIP_Str_2
set_location_assignment PIN_P1 -to DIP_Str_1
set_location_assignment PIN_R1 -to DIP_Str_4
set_location_assignment PIN_L2 -to DIP_Str_3
set_location_assignment PIN_R8 -to Mem_prot
set_location_assignment PIN_T8 -to Advance
set_location_assignment PIN_R9 -to up_down
set_location_assignment PIN_K16 -to SPC_Sol_Trig[2]
set_location_assignment PIN_J16 -to SPC_Sol_Trig[3]
set_location_assignment PIN_J15 -to SPC_Sol_Trig[4]
set_location_assignment PIN_G16 -to SPC_Sol_Trig[1]
set_location_assignment PIN_A14 -to SPC_Sol_Trig[5]
set_location_assignment PIN_B14 -to SPC_Sol_Trig[6]
set_location_assignment PIN_B4 -to reset_sw
set_location_assignment PIN_C9 -to LED_active
set_location_assignment PIN_D9 -to LED_SD_Error
set_location_assignment PIN_C6 -to LED_status
set_location_assignment PIN_P16 -to Diag_SW
set_location_assignment PIN_P15 -to Enter_SW
set_location_assignment PIN_B5 -to sound_com_sel
set_location_assignment PIN_L15 -to W_PA_DIP[0]
set_location_assignment PIN_N15 -to W_PA_DIP[1]
set_location_assignment PIN_N16 -to W_PA_DIP[2]
set_location_assignment PIN_L16 -to W_PA_DIP[3]
set_location_assignment PIN_T2 -to USB_Rx
set_location_assignment PIN_R3 -to USB_Tx
set_location_assignment PIN_N14 -to debug
