@{
    Name        = 's_cyclone_iv_v4'
    Title       = 'WillFA7S HW1.0 with sound board, Cyclone IV (EP4CE10E22C8)'
    BoardId     = 6
    RtlFamily   = 'cyclone_iv_s'
    Options     = @('sound')
    BinFolder   = ''
    ReleaseArtifact = 'jic'

    # DORMANT. Skipped by check.ps1, build.ps1 and release.ps1 unless -All is given,
    # and NOT generated by gen_qsf.ps1 - this variant has its own top level and its
    # own frozen copies of the common modules under local/, so it does not fit the
    # shared model. See README.md in this folder.
    Dormant     = $true
    Generated   = $false

    VirtualPins = @()
    Notes       = 'Does not build. The .qip paths are fixed now, but real VHDL errors remain underneath.'
}
