@{
    Name        = 's_cyclone_10'
    Title       = 'WillFA7S HW1.0 with sound board, Cyclone 10 LP (10CL010YE144C6G)'
    BoardId     = 7
    RtlFamily   = 'cyclone_10_s'
    Options     = @('sound')
    BinFolder   = ''
    ReleaseArtifact = 'jic'

    # DORMANT and unfinished. Skipped by check.ps1, build.ps1 and release.ps1 unless
    # -All is given, and NOT generated by gen_qsf.ps1 - own top level, own frozen
    # copies of the common modules under local/. See README.md in this folder.
    Dormant     = $true
    Generated   = $false

    VirtualPins = @()
    Notes       = 'Does not build, and has zero pin assignments. Unfinished.'
}
